# Generated by Django 6.0 on 2026-01-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='correction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
