# Generated by Django 6.0 on 2026-01-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_predictionhistory_correction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
